version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"  # Map port 27017 inside the container to port 27017 on your machine
    volumes:
      - mongo-data:/data/db  # Persistent storage for MongoDB data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: unless-stopped

volumes:
  mongo-data:
    driver: local
