apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  # Disable HTTPS redirection (if needed)
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"  # Ensures HTTP traffic is routed properly
spec:
  ingressClassName: nginx  # Ensures this Ingress is handled by NGINX
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nodejs-service
                port:
                  number: 80