global:
  scrape_interval: 5s  # Scrape every 5 seconds

scrape_configs:
  # - job_name: 'hello-world-metrics'
  #   static_configs:
  #     - targets: ['host.docker.internal:4000']  # Target the Hello World app on port 4000
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']