name: Node.js Build & Docker Build Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  clone:
    name: Clone Repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

  dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    needs: clone  # This job depends on the clone job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Fix Dependency Conflicts (Downgrade React)
        run: npm install react@18.2.0 react-dom@18.2.0 --legacy-peer-deps

      - name: Install Next.js
        run: npm install next --legacy-peer-deps

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-${{ runner.os }}-

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: dependencies  # Depends on dependencies being installed first
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Restore Cached Node Modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Build Project
        run: npm run build --if-present

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: node-build
          path: .  # Adjust if needed

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: build  # Depends on the build job finishing
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: node-build
          path: .  # Adjust if needed

      - name: Set Up Docker
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t my-app:latest .

      - name: Push Docker Image (Optional)
        run: docker push my-app:latest
        if: github.event_name == 'push'
